repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
-   repo: https://github.com/fsouza/autoflake8
    rev: v0.4.0
    hooks:
    -   id: autoflake8
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.294
  hooks:
  - id: pyright