version: "3.9"
services:
  web:
    build: .
    ports:
      - 8001:80
    volumes:
      - ./app/app:/app/app
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379