mixed_precision: null
seed: null
pretrained_model_name_or_path: null
revision: null
image_column: "image"
caption_column: "text"
max_train_samples: null
cache_dir: /tmp/
center_crop: false
random_flip: false
train_batch_size: 16
num_train_epochs: 100
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 1e-4
scale_lr: false
lr_scheduler: "constant"
lr_warmup_steps: 500
use_8bit_adam: false
allow_tf32: false
use_ema: false
non_ema_revision: null
dataloader_num_workers: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-08
max_grad_norm: 1.0
max_train_steps: null
resume_from_checkpoint: 500
enable_xformers_memory_efficient_attention: false